# kubernetes/cluster/home-lab/flux-system/infra.yaml
---
# Cilium CNI
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cilium
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infra/cilium/
  prune: true
  wait: true
  timeout: 5m0s
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cilium
      namespace: kube-system

---
# Cilium related policies (eg L2 Announcements, Load balancing IP Pools)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-networking
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-cilium
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infra/networking/
  prune: true
  wait: true
  timeout: 5m0s

---
# Storage for the cluster
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-storage
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infra/storage/
  prune: true
  wait: true
  timeout: 5m0s

---
# Ingress Controller
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-ingress
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infra/ingress/
  prune: true
  wait: true
  timeout: 5m0s

---
# Infrastructure related tools (eg Kubernetes dashboard, metrics-server, etc)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-tools
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infra/tools/
  prune: true
  wait: true
  timeout: 5m0s
