---
extends: "default"
rules:
  comments: "enable"
  comments-indentation: "disable"
  empty-values: "enable"
  indentation:
    spaces: 2
    indent-sequences: "consistent"
  line-length: "disable"
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  truthy: disable
ignore: |
  .venv
  kubernetes/clusters/*/flux-system/
  *secrets.yaml
