# kubernetes/apps/nautobot/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nautobot
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml

configMapGenerator:
  - name: nautobot-values
    namespace: nautobot
    files:
      - values.yaml=values.yaml
  - name: nautobot-config
    namespace: nautobot
    files:
      - nautobot_config.py=nautobot_config.py

secretGenerator:
  - name: nautobot-secrets
    namespace: nautobot
    files:
      - secrets.yaml=secrets.yaml

configurations:
  - kustomizeconfig.yaml