---
# Nautobot Server
nautobot:
  # -- Number of Nautobot server replicas to deploy
  replicaCount: 2

postgresql:
  # -- Enable deployment of the [Bitnami postgresql](https://github.com/bitnami/charts/tree/master/bitnami/postgresql) chart, all other `postgresql.*` parameters will be passed directly to that chart
  enabled: true

redis:
  # -- Enable deployment of the [Bitnami redis](https://github.com/bitnami/charts/tree/master/bitnami/redis) chart, all other `redis.*` parameters will be passed directly to that chart
  enabled: true

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: "nautobot.home.lab"
  # -- The backend protocol to for the Ingress to communicate with the Nautobot containers, valid values: http, and https
  backendProtocol: "http"
