# kubernetes/infra/monitoring/controllers/release.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  interval: 20m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "58.x.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 10m

  valuesFrom:
    - kind: ConfigMap
      name: flux-kube-state-metrics-config
      valuesKey: kube-state-metrics-config.yaml

  values:
    prometheus:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - prometheus.home.lab
      prometheusSpec:
        podMonitorNamespaceSelector: { }
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring

    grafana:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - grafana.home.lab
