# kubernetes/infra/monitoring/controllers/repository.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 120m0s
  url: https://prometheus-community.github.io/helm-charts
