# kubernetes/infra/cilium/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cilium
  namespace: kube-system
resources:
  - repository.yaml
  - release.yaml
