# kubernetes/infra/cilium/repository.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 120m0s
  url: https://helm.cilium.io/
