# kubernetes/infra/ingress/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ingress-nginx
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
