apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: '>=1.15.1'
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      interval: 1m
  values:
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
    k8sClientRateLimit:
      burst: 100
      qps: 50
    k8sServiceHost: 192.168.1.160
    k8sServicePort: 6443
    kubeProxyReplacement: true
    l2announcements:
      enabled: true
