# apiVersion: helm.toolkit.fluxcd.io/v2beta2
# kind: HelmRelease
# metadata:
#   name: cilium
#   namespace: kube-system
# spec:
#   interval: 5m
#   chart:
#     spec:
#       chart:
#       version: '4.0.x'
#       sourceRef:
#         kind: <HelmRepository|GitRepository|Bucket>
#         name: podinfo
#         namespace: flux-system
#       interval: 1m
#   values:
#     replicaCount: 2
