# kubernetes/infra/tools/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infra-tools
  namespace: kube-system
resources:
  - repository.yaml
  - release.yaml
