# kubernetes/infra/tools/release.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 20m
  chart:
    spec:
      chart: metrics-server
      version: "3.12.0"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      interval: 10m
  values:
    args:
      - --kubelet-insecure-tls
