# kubernetes/infra/tools/release.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  interval: 20m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "58.x.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 10m

  values:
    prometheus:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - prometheus.home.lab

    grafana:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - grafana.home.lab
