# kubernetes/infra/tools/repository.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 90m0s
  url: https://kubernetes-sigs.github.io/metrics-server/
