# kubernetes/infra/networking/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cilium
  namespace: kube-system
resources:
  - l2-policy.yaml
  - lb-ip-pool.yaml
