# kubernetes/infra/networking/lb-ip-pool.yaml
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "home-lab-lb-ip-pool"
spec:
  blocks:
    - start: 192.168.1.200
      stop: 192.168.1.240
