# kubernetes/infra/tools/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: longhorn-kustom
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml